### ISSUE TITLE
taipo not reading yml file correctly

### ISSUE THREAD

**Issue by bubjanes** [RasaHQ/taipo#13]
**OS**: macOS Big Sur 11.4
**rasa version** : 2.7.1
**rasa-sdk**: 2.7.0
**taipo**: 0.0.1
**nluaug**: 1.1.4

**Issue**:

Installed taipo successfully (```python -m taipo keyboard augment --help``` worked correctly). However, when I attempt to generate data the program appears unable to read my **nlu.yml** file. The following traceback is generated:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/taipo/__main__.py", line 22, in <module>
    app()
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/taipo/cli/keyboard.py", line 48, in augment
    dataf = nlu_path_to_dataframe(file)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/taipo/common.py", line 23, in nlu_path_to_dataframe
    intent=lambda d: d["nlu"]["intent"],
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/clumper/decorators.py", line 34, in wrapped
    return method(clumper, *args, **kwargs)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/clumper/clump.py", line 1218, in mutate
    new[key] = func(new)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/taipo/common.py", line 23, in <lambda>
    intent=lambda d: d["nlu"]["intent"],
KeyError: 'intent'
```

In case it is helpful, the head of my **nlu.yml** file looks like this:

```
version: "2.0"
nlu:
- intent: greet
  examples: |
    - hola
    - hello man
    - buen dia
    - Hola buenos dias
    - hola, buen día
```

**Command that led to error**:
```python -m taipo keyboard augment data/nlu.yml data/bad-spelling-nlu.yml```

**Comment by koaning** [comment]
I just created a new file called `nlu.yml` that contains the following contents. 

```yml
version: "2.0"
nlu:
- intent: greet
  examples: |
    - hola
    - hello man
    - buen dia
    - Hola buenos dias
    - hola, buen día
```

I then proceeded to run taipo via; 

```
python -m taipo keyboard augment nlu.yml foobar.yml
```

This works on my end.  Could you try with your file? 

There *might* be an issue with your `nlu.yml` file also having non-intents in the file. Do you have regexes in there? If so, this is an issue that I need to double-check.

**Comment by koaning** [comment]
Also, are you sure you upgraded the version? I'm running `0.0.2`. You can re-install via; 

```
python -m pip install --upgrade "taipo @ git+https://github.com/RasaHQ/taipo.git"
```

**Comment by bubjanes** [comment]
Running version ```0.0.2``` but that's not the problem, I don't think. I'm pretty sure it was my synonyms, e.g.:

```
- synonym: cordoba
  examples: |
    - córdoba
    - Córdoba
    - cordova
    - Córdova
    - Cordoba
    - córdova
    - cordoba
- synonym: buenos aires
  examples: |
    - Buenos Aires
    - Baires
    - bs. as
```

I commented these out and it appeared to have worked fine. So maybe there's an improvement to be made: "ignores synonyms". Should we make a seperate issue or just use this one?

**Comment by koaning** [comment]
It's likely also regexes/lookups then. I think it should be a simple matter of adapting the `nlu_path_to_dataframe` method in the `common.py` file. Feel free to make a PR for that. 

For bonus points: feel free to change the datasets that we use in the `/tests` folder such that they also contain `synonym`.

**Comment by bubjanes** [comment]
Will do @koaning! 🔥

**Comment by koaning** [comment]
Fixed by linked PR.
