### ISSUE TITLE
module not found after installation

### ISSUE THREAD

**Issue by bubjanes** [RasaHQ/taipo#9]
**OS**: macOS Big Sur 11.4
**rasa version** : 2.7.1
**rasa-sdk**: 2.7.0
**taipo**: 0.0.1
**nluaug**: 1.1.4

**Issue**:

After following installation instructions on README.md  (```python -m pip install "taipo @ git+https://github.com/RasaHQ/taipo.git"```) the program does not execute and produces the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brandonjanes/Desktop/covid_19_bot/env/lib/python3.7/site-packages/taipo/__main__.py", line 3, in <module>
    from taipo.cli.keyboard import app as keyboard_app
ModuleNotFoundError: No module named 'taipo.cli'
```

**Command that led to error**:
```python -m taipo```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koernerfelicia will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
That's quite strange. Will investigate right away!

**Comment by koaning** [comment]
I've been able to reproduce this. It installs fine, until you try to run it. 

```
> python -m pip freeze | grep tai                                        
altair==4.1.0
taipo==0.0.1
> python -m taipo
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vincent/Development/tokenwiser/venv/lib/python3.7/site-packages/taipo/__main__.py", line 3, in <module>
    from taipo.cli.keyboard import app as keyboard_app
ModuleNotFoundError: No module named 'taipo.cli'
```

Very strange though.

**Comment by koaning** [comment]
Ah yeah. It was all due to a missing`__init__.py` file. It's interesting to see the unit tests not picking this up, will investigate that later. I just ran it locally and it should work now. Thanks for reporting!

**Comment by bubjanes** [comment]
Glad you found it! Thanks! 🔥
